### ISSUE TITLE
Is this for Android only ?

### ISSUE THREAD

**Issue by amitbravo** [Suraj-Tiwari/react-native-payumoney#1]
Is this for Android only ? and Is this a wrapper around payumoney android SDK ?

**Comment by Suraj-Tiwari** [comment]
Yes for now.. I'll work on IOS version too.

**Comment by amitbravo** [comment]
When we can expect for iOS, just wondering.

**Comment by Suraj-Tiwari** [comment]
Well, Due to my hell busy schedules i can't manage time for ios Module ATM. All PR's are welcome
