### ISSUE TITLE
com.android.support:support-v4 version Issue

### ISSUE THREAD

**Issue by akshay1293** [Suraj-Tiwari/react-native-payumoney#10]
I think this issue is related to compatibility with RN 0.57

Iam using React native 0.57.4
Gradle - 3.1.4
react - 16.6.0-alpha.8af6728

Please provide support for RN 0.57

I am getting this error while building App

Android dependency 'com.android.support:support-v4' has different version for the compile (23.2.1) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution

**Comment by maac4422** [comment]
@akshay1293 What is your compile SDK?

**Comment by akshay1293** [comment]
@Suraj-Tiwari 

here
buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"

If I remove react-native-payumoney and then build again then everything works fine.

**Comment by maac4422** [comment]
@akshay1293  Try change inside your **App Level Gradle File**

`implementation (project(':react-native-payumoney'))`
to

```
implementation (project(':react-native-payumoney')) {
        exclude group: "com.android.support"
}
implementation "com.android.support:exifinterface:+"
  implementation "com.android.support:support-annotations:+"
  implementation "com.android.support:support-v4:+"
```

**Comment by Suraj-Tiwari** [comment]
@akshay1293 if you still have issue please share the output of `./gradlew app:dependencies`

**Comment by akshay1293** [comment]
@maac4422    Doing this results in below error.

     /home/.gradle/caches/transforms-1/files-1.1/appcompat-v7-
     27.1.1.aar/f57ff26f0e1f39643fb1b36e9f7f53d2/res/values/values.xml:251:5-69: AAPT: error: resource 
     android:attr/ttcIndex not found.

These are the dependencies.
```

dependencies {
    implementation (project(':react-native-payumoney')) {
        exclude group: "com.android.support"
}
implementation "com.android.support:exifinterface:+"
  implementation "com.android.support:support-annotations:+"
  implementation "com.android.support:support-v4:+"
    compile project(':react-native-keep-awake')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-google-signin')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}
```
@Suraj-Tiwari  And do you want me to post whole output of ./gradlew app:dependencies?

**Comment by maac4422** [comment]
@akshay1293 try with this

`implementation "com.android.support:exifinterface:${rootProject.ext.supportLibVersion}"
  implementation "com.android.support:support-annotations:${rootProject.ext.supportLibVersion}"
  implementation "com.android.support:support-v4:${rootProject.ext.supportLibVersion}"`

**Comment by indranildutta06** [comment]
If you are having the same problem still now then change the compileSdkVersion to 28 and targetSdkVersion to 28 too. BuildToolVersion can be 28.0.2

**Comment by Suraj-Tiwari** [comment]
Closed due to inactivity
