### ISSUE TITLE
[WIP] iOS support for payumoney

### ISSUE THREAD

**Issue by ram4git** [Suraj-Tiwari/react-native-payumoney#11]
This library already has android support that is tested and working. To make it a **complete** react-native library, it would be awesome if the missing iOS support is also added.

Just the right wrapper around the native module with bridge to work just how awesomely it works with android

**Comment by rrakesh100** [comment]
+1

**Comment by Suraj-Tiwari** [comment]
IOS Support added (Still in dev mode) check ios branch 

// IOS test credentials are 
Merchant Key = "mdyCKV"
Merchant ID = "4914106"
Merchant Salt = "Je7q3652"

// These are the test card credentials. 
Card No - 5123456789012346
Expiry - 05/2020
CVV - 123
