### ISSUE TITLE
Upgrade dependency to compile:com.payumoney.sdkui:plug-n-play:1.4.4

### ISSUE THREAD

**Issue by Gvinod1991** [Suraj-Tiwari/react-native-payumoney#13]
**Feature request related to a problem is described below**
Now sdkui:plug-n-play:1.0.0 is the dependency in this package.I have tested this package by integrating in react native app.In my app card payments not working and in net banking option some banks like SBI throwing the error even after payment successfully done.

**Solution to the problem**
Upgrade the dependency sdkui:plug-n-play:1.0.0 to sdkui:plug-n-play:1.4.4 .

**Comment by Suraj-Tiwari** [comment]
Thanks for reporting the issue. I'll have a look at it.

**Comment by Gvinod1991** [comment]
Can you help me to fix the problem @Suraj-Tiwari. As i am js developer, don't have deep knowledge in native android app development. If you share some knowledge to solve the problem i will try to fix it.

**Comment by Gvinod1991** [comment]
I have used alternate way to integrate payment gateway is that wrap web app payment system in webView of react native.

**Comment by Suraj-Tiwari** [comment]
Good, but web payment is against Google Policy i guess
