### ISSUE TITLE
What's the status for the iOS support?

### ISSUE THREAD

**Issue by romit07** [Suraj-Tiwari/react-native-payumoney#15]

**Comment by Suraj-Tiwari** [comment]
Please check Ios branch that's done,
Need some improvement but i don't have enough time for now.

**Comment by romit07** [comment]
Is there any known issue there? what improvements you mentioned so that I can go through it

**Comment by Suraj-Tiwari** [comment]
Currently Hash is calculated in app,
Make it direct that's it.

**Comment by Suraj-Tiwari** [comment]
Closed due to inactivity

**Comment by Suraj-Tiwari** [comment]
Closed due to inactivity
