### ISSUE TITLE
{ success: false } error

### ISSUE THREAD

**Issue by appsleal** [Suraj-Tiwari/react-native-payumoney#16]
web calculating hash
![Captura de pantalla (24)](https://user-images.githubusercontent.com/49653660/56710332-35f35d00-66eb-11e9-86f5-b0106455c474.png)

**Comment by Suraj-Tiwari** [comment]
Make sure your hash is calculated correctly.
for this check logcat and find hash and match it with your hash.

**Comment by appsleal** [comment]
@Suraj-Tiwari  It's strange when I use your example data, I execute perfectly, but when I put my account information, it returns error

**Comment by Suraj-Tiwari** [comment]
Issue could be related to hash calculation, also check amount data type and
value,
that create issue too.

**Comment by appsleal** [comment]
it does not make sense because I use the same data just change the account info with your test works with mine does not work

**Comment by Suraj-Tiwari** [comment]
is that in debug or production?
Because credentials provided in dashboard doesn't work for debug ang they
will throw an error

**Comment by vishnujnv15** [comment]
@appsleal  how did you solve this issue
