### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by saurabh-nandan** [Suraj-Tiwari/react-native-payumoney#17]
**Describe the bug**
I am using payumoney for react native app. I have installed this library but couldnot able to sucessfully execute due to an error "Native module cannot be null"

i am working on this environment:-
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-payumoney": "0.0.3"

Please resolve this issue asap i am stuck with it.

PFA for the references.
Thanks.

![Simulator Screen Shot - iPhone X - 2019-06-18 at 12 26 05](https://user-images.githubusercontent.com/47634223/59659801-958a5800-91c4-11e9-9bdc-d572db7c6d61.png)

**Comment by ankitnb** [comment]
Hey, did you get resolved this issue in iOS? I am having the same issue.

**Comment by Suraj-Tiwari** [comment]
for ios please install module from github repo
then run react-native link react-native-payumoney

**Comment by ankitnb** [comment]
I installed with these steps:
1) $ npm i react-native-payumoney --save
2) $ react-native link react-native-payumoney

what I have to install else?

**Comment by Suraj-Tiwari** [comment]
change step 1 to
npm i {repo link}

**Comment by ankitnb** [comment]
which repo link? of iOS ?
can you please describe me in detail?

**Comment by Suraj-Tiwari** [comment]
This github repo link

**Comment by ankitnb** [comment]
I installed with,
`npm i https://github.com/Suraj-Tiwari/react-native-payumoney.git`

but still I face same issue.

**Comment by Suraj-Tiwari** [comment]
link again

**Comment by ankitnb** [comment]
Linked but getting errors in iOS code, do I have to replace any code for iOS files?
![Screen Shot 2019-07-08 at 5 37 04 PM](https://user-images.githubusercontent.com/52659109/60808949-1aa2d480-a1a7-11e9-9c3b-27d4ead786c3.png)

**Comment by ankitnb** [comment]
Can you please send me `react-native-payumoney` folder from `node modules` ? because I am getting errors for iOS code, I tried with inserting iOS frameworks but still It is not correcting.

**Comment by ankitnb** [comment]
Suraj, Does it require to add Frameworks from Native SDK for iOS ? Because I am getting above errors for iOS Code.

**Comment by ankitnb** [comment]
Guys, I found solution of it.
After installing `pod 'PayUmoney_PnP'` pods, it worked for me.

**Comment by jrsarath** [comment]
Please close this issue if resolved

**Comment by Pawanjot3015** [comment]
> Guys, I found solution of it.
> After installing `pod 'PayUmoney_PnP'` pods, it worked for me.

not working for me
still facing Use of undeclared identifier PUMTxnParam
