### ISSUE TITLE
Getting error native module cannot be null while installing with pods(pod 'PayUmoney_PnP') in IOS

### ISSUE THREAD

**Issue by srichallamalla935** [Suraj-Tiwari/react-native-payumoney#26]
Installing the react-native-payu module using pods `(pod 'PayUmoney_PnP')`  and after that i kept import statement  but  i am facing **native module cannot be null**  error

### Versions
react-native :-0.60.5
 react-native-payu:-0.0.3

### ScreenShot
![Simulator Screen Shot - iPhone 5s - 2019-09-24 at 10 23 32](https://user-images.githubusercontent.com/45194188/65482347-63208300-deb6-11e9-979b-ddcbb4b93415.png)

**Comment by Suraj-Tiwari** [comment]
Hi,
It looks like you're using it from NPM,
Please note IOS is completely expiremental for now, you can directly
install it from github repo.

**Comment by Harikasai999** [comment]
I installed with this npm `npm i https://github.com/Suraj-Tiwari/react-native-payumoney.git` in react-native 0.60.5. But i am facing same issue **native module cannot be null**.

**Comment by Benzen8** [comment]
still facing the same issue also after the pod 'PayUmoney_PnP', adding path to the `pod 'PayUmoney_PnP', :path => "../node_modules/react-native-payumoney/"` and the pod spec file is required.

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed. IOS support added
