### ISSUE TITLE
Getting issue in RN 0.59

### ISSUE THREAD

**Issue by Anujmoglix** [Suraj-Tiwari/react-native-payumoney#29]
Task :react-native-payumoney:compileDebugJavaWithJavac FAILED
node_modules/react-native-payumoney/android/src/main/java/superinfotech/suraj/reactnativepayumoney/PayumoneyModule.java:9: error: package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivit

**Comment by Anujmoglix** [comment]
Is anyone handling this repo?

**Comment by Ritesh175862** [comment]
> Is anyone handling this repo?



> Task :react-native-payumoney:compileDebugJavaWithJavac FAILED
> node_modules/react-native-payumoney/android/src/main/java/superinfotech/suraj/reactnativepayumoney/PayumoneyModule.java:9: error: package android.support.v7.app does not exist
> import android.support.v7.app.AppCompatActivit

just replay this line with this import androidx.appcompat.app.AppCompatActivity;

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
