### ISSUE TITLE
some error occured

### ISSUE THREAD

**Issue by ashu777** [Suraj-Tiwari/react-native-payumoney#30]
i integrated react-native-payumoney as per your instructions. i am able to generate hash.After generating hash it shows some error occured and success:false in log. it is integrated to a website and working fine but in case of android i used your library it is not working if i use the hash, marchant key and id you provided it works but my credentials are not working.

**Comment by Suraj-Tiwari** [comment]
if your credentials aren't working and test credentials are working. Then,
there might be some other issue, please share logs from logcat.

**Comment by ashu777** [comment]
amount: 99.9
email: "test@gmail.com"
furl: "https://www.example.com/payu-validate.php"
hash: "a87a2d1f4ca0f8805be903d6965b832724b7ef41d2cb1bd805c3ea5c378ea3d8d5cafee0a66d227f3339857c9152301432f5705725bfd03c4cb1fce7248b0930"
id: "xxxxxxx"
key: "xxxxxxx"
name: "AD"
phone: "7894123489"
productId: "123"
sandbox: true
surl: "https://www.example.com/payu-validate.php"
txid: "545446545"



success: false

**Comment by ashu777** [comment]
I am getting the above while i  log the options  in console .

**Comment by vgvishal538** [comment]
@ashu777 @Suraj-Tiwari did you guy finds any solution for this issue?

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
