### ISSUE TITLE
issue in installing 

### ISSUE THREAD

**Issue by Anujmoglix** [Suraj-Tiwari/react-native-payumoney#31]
HI , 
  I am getting following issue after installing and linking the project 

> 
> **Task :react-native-payumoney:compileDebugJavaWithJavac FAILED**
> App/node_modules/react-native-payumoney/android/src/main/java/superinfotech/suraj/reactnativepayumoney/PayumoneyModule.java:9: error: package android.support.v7.app does not exist
> import android.support.v7.app.AppCompatActivity;

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
