### ISSUE TITLE
Use of undeclared identifier PUMTxnParam

### ISSUE THREAD

**Issue by Pawanjot3015** [Suraj-Tiwari/react-native-payumoney#33]

**Comment by hibittushah** [comment]
Hey Can you please look into this .I am getting this issue when i am running in my physical device
Android resource linking failed
C:\Users\username.gradle\caches\transforms-2\files-2.1\5a0aebce116225012ffd37f82b441a81\jetified-magicretry-1.0.5\res\layout-v11\magicretry_fragment.xml:131: AAPT: error: resource android:attr/android:progressBarStyleSmall
not found.

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
