### ISSUE TITLE
App crashing on sandbox:true

### ISSUE THREAD

**Issue by basilbthoppil** [Suraj-Tiwari/react-native-payumoney#34]
Payment flow is working fine with sandbox:false,

whenever the sandbox:true the app crashes without any specific error in adb log

Tried with parameters in example app, in the same repo. still fails.

`let options = {
            amount: "10.0",
            txid: "123123123" ,
            productId: "test",
            name: "Name",
            email: "test@gmail.com",
            phone: "8826343434",
            id: "4914106",
            key: "mdyCKV",
            surl: "https://www.payumoney.com/mobileapp/payumoney/success.php",
            furl: "https://www.payumoney.com/mobileapp/payumoney/failure.php",
            sandbox: true,
            hash: "f1c2830db04e388433db0857ca00a9f918ee64b070e45a4c2525a9f4b7df602d6d82f2b187bca7a595c5c7f15ee29349c50f11c5a99d0c29a735423486852b7b"
        };`

With these params, app crashes.

**Comment by hibittushah** [comment]
Hey Can you please look into this .I am getting this issue when i am running in my physical device 
Android resource linking failed
     C:\Users\username\.gradle\caches\transforms-2\files-2.1\5a0aebce116225012ffd37f82b441a81\jetified-magicretry-1.0.5\res\layout-v11\magicretry_fragment.xml:131: AAPT: error: resource android:attr/android:progressBarStyleSmall 
not found.

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
