### ISSUE TITLE
 Android resource linking failed

### ISSUE THREAD

**Issue by hibittushah** [Suraj-Tiwari/react-native-payumoney#35]
Please anyone know about this how to resolve this 

     C:\Users\username\.gradle\caches\transforms-2\files-2.1\5a0aebce116225012ffd37f82b441a81\jetified-magicretry-1.0.5\res\layout-v11\magicretry_fragment.xml:131: AAPT: error: resource android:attr/android:progressBarStyleSmall not found.

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
