### ISSUE TITLE
When click on payment button got this error

### ISSUE THREAD

**Issue by Shaileshr777** [Suraj-Tiwari/react-native-payumoney#36]
**PAYU_PAYMENT_FAILED{error:true}**

This is my code
fetch('http://115.124.127.118/~devfds/covid19_app_api/hash.php', {
    method: 'POST',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    },
    body: JSON.stringify({
        key: key,
        txnid: txid,
        amount: amount,
        productinfo: productId,
        firstname: name,
        email: email
    }),
})
    .then((response) => response.text())
    .then((hash) => {

        console.log("Shailesh repos"+hash)
        let options = {
            amount: amount,
            txid: txid ,
            productId: productId,
            name: name,
            email: email,
            phone: phone,
            id: id,
            key: key,
            surl: surl,
            furl: furl,
            sandbox: sandbox,
            hash: hash
        };
        console.log(options);
        PayuMoney.pay(options).then((d) => {
            console.log(d); // WIll get a Success response with verification hash
        }).catch(e => {
            console.log(e); //In case of failture
        });
    })

**Comment by Shaileshr777** [comment]
Getting toast message 'Some error occur'

**Comment by Suraj-Tiwari** [comment]
#38 version 1.0.0 released all known issue fixed
