### ISSUE TITLE
IOS prod screen mode not opening 

### ISSUE THREAD

**Issue by Moumit** [Suraj-Tiwari/react-native-payumoney#44]
//Below line is not working, it's always showing test card screen
`txnParam.environment = payuData[@"isDebug"]?PUMEnvironmentTest:PUMEnvironmentProduction;`

Passed parameter
```
{
......
isDebug:false
...
}
```

not working

**Comment by Suraj-Tiwari** [comment]
you tried removing condition and hardCoding it to? if yes was that effective? 

`txnParam.environment = PUMEnvironmentProduction;`

**Comment by Moumit** [comment]
Yes by hardcode i had to publish the app, that worked .. i think the trinary operator not working

**Comment by Suraj-Tiwari** [comment]
okay I'll have a look at it thanks for your info.

**Comment by Suraj-Tiwari** [comment]
Fixed is #55
