### ISSUE TITLE
Ios into Not Working.

### ISSUE THREAD

**Issue by dhavalgediya27** [Suraj-Tiwari/react-native-payumoney#50]
I am call the payumoney method in ios then my application is crashed.
My app Crash Log is.

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001ebe3b0dc 0x1ebe18000 + 143580
1   libsystem_pthread.dylib       	0x00000001ebeb4094 0x1ebeb2000 + 8340
2   libsystem_c.dylib             	0x00000001ebd93ea8 0x1ebd39000 + 372392
3   libc++abi.dylib               	0x00000001eb460788 0x1eb45f000 + 6024
4   libc++abi.dylib               	0x00000001eb460934 0x1eb45f000 + 6452
5   libobjc.A.dylib               	0x00000001eb477e00 0x1eb472000 + 24064
6   libc++abi.dylib               	0x00000001eb46c838 0x1eb45f000 + 55352
7   libc++abi.dylib               	0x00000001eb46c8c4 0x1eb45f000 + 55492
8   libdispatch.dylib             	0x00000001ebcdd7e8 0x1ebc7d000 + 395240
9   libdispatch.dylib             	0x00000001ebc8bcec 0x1ebc7d000 + 60652
10  libdispatch.dylib             	0x00000001ebcdd7d4 0x1ebc7d000 + 395220
11  libdispatch.dylib             	0x00000001ebc8b008 0x1ebc7d000 + 57352
12  CoreFoundation                	0x00000001ec230b20 0x1ec186000 + 699168
13  CoreFoundation                	0x00000001ec22ba58 0x1ec186000 + 678488
14  CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
15  GraphicsServices              	0x00000001ee42c79c 0x1ee422000 + 42908
16  UIKitCore                     	0x0000000218c71c38 0x2183b5000 + 9161784
17  padkranti                     	0x00000001006155cc 0x100610000 + 21964
18  libdyld.dylib                 	0x00000001ebcee8e0 0x1ebced000 + 6368

Thread 1:
0   libsystem_pthread.dylib       	0x00000001ebec0cd0 0x1ebeb2000 + 60624

Thread 2 name:  Dispatch queue: com.facebook.react.RNPayumoneyQueue
Thread 2:
0   libsystem_kernel.dylib        	0x00000001ebe3b9d4 0x1ebe18000 + 145876
1   libdispatch.dylib             	0x00000001ebc7fa5c 0x1ebc7d000 + 10844
2   libdispatch.dylib             	0x00000001ebc7fb94 0x1ebc7d000 + 11156
3   libdispatch.dylib             	0x00000001ebc8bec0 0x1ebc7d000 + 61120
4   libdispatch.dylib             	0x00000001ebc8bad8 0x1ebc7d000 + 60120
5   padkranti                     	0x0000000100a82c3c 0x100610000 + 4664380
6   CoreFoundation                	0x00000001ec2a6800 0x1ec186000 + 1181696
7   CoreFoundation                	0x00000001ec1883c0 0x1ec186000 + 9152
8   CoreFoundation                	0x00000001ec188ff4 0x1ec186000 + 12276
9   padkranti                     	0x00000001007c58cc 0x100610000 + 1792204
10  padkranti                     	0x00000001007c8f94 0x100610000 + 1806228
11  padkranti                     	0x00000001007c8b48 0x100610000 + 1805128
12  padkranti                     	0x00000001007c8abc 0x100610000 + 1804988
13  libdispatch.dylib             	0x00000001ebcdca38 0x1ebc7d000 + 391736
14  libdispatch.dylib             	0x00000001ebcdd7d4 0x1ebc7d000 + 395220
15  libdispatch.dylib             	0x00000001ebc86324 0x1ebc7d000 + 37668
16  libdispatch.dylib             	0x00000001ebc86e40 0x1ebc7d000 + 40512
17  libdispatch.dylib             	0x00000001ebc8f4ac 0x1ebc7d000 + 74924
18  libsystem_pthread.dylib       	0x00000001ebebe114 0x1ebeb2000 + 49428
19  libsystem_pthread.dylib       	0x00000001ebec0cd4 0x1ebeb2000 + 60628

Thread 3:
0   libsystem_pthread.dylib       	0x00000001ebec0cd0 0x1ebeb2000 + 60624

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0   libsystem_kernel.dylib        	0x00000001ebe300f4 0x1ebe18000 + 98548
1   libsystem_kernel.dylib        	0x00000001ebe2f5a0 0x1ebe18000 + 95648
2   CoreFoundation                	0x00000001ec230914 0x1ec186000 + 698644
3   CoreFoundation                	0x00000001ec22b824 0x1ec186000 + 677924
4   CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
5   Foundation                    	0x00000001ecbf995c 0x1ecbf2000 + 31068
6   Foundation                    	0x00000001ecbf97ec 0x1ecbf2000 + 30700
7   UIKitCore                     	0x0000000218d57754 0x2183b5000 + 10102612
8   Foundation                    	0x00000001ecd264a0 0x1ecbf2000 + 1262752
9   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
10  libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
11  libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 5 name:  com.facebook.react.JavaScript
Thread 5:
0   libsystem_kernel.dylib        	0x00000001ebe300f4 0x1ebe18000 + 98548
1   libsystem_kernel.dylib        	0x00000001ebe2f5a0 0x1ebe18000 + 95648
2   CoreFoundation                	0x00000001ec230914 0x1ec186000 + 698644
3   CoreFoundation                	0x00000001ec22b824 0x1ec186000 + 677924
4   CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
5   padkranti                     	0x000000010074fdf0 0x100610000 + 1310192
6   Foundation                    	0x00000001ecd264a0 0x1ecbf2000 + 1262752
7   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
8   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
9   libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 6 name:  JavaScriptCore bmalloc scavenger
Thread 6:
0   libsystem_kernel.dylib        	0x00000001ebe3aee4 0x1ebe18000 + 143076
1   libsystem_pthread.dylib       	0x00000001ebeb5cf8 0x1ebeb2000 + 15608
2   libc++.1.dylib                	0x00000001eb411128 0x1eb409000 + 33064
3   JavaScriptCore                	0x00000001f34cb304 0x1f343c000 + 586500
4   JavaScriptCore                	0x00000001f34cb1b4 0x1f343c000 + 586164
5   JavaScriptCore                	0x00000001f34c9e4c 0x1f343c000 + 581196
6   JavaScriptCore                	0x00000001f34c954c 0x1f343c000 + 578892
7   JavaScriptCore                	0x00000001f34caf8c 0x1f343c000 + 585612
8   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
9   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
10  libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 7 name:  com.squareup.SocketRocket.NetworkThread
Thread 7:
0   libsystem_kernel.dylib        	0x00000001ebe300f4 0x1ebe18000 + 98548
1   libsystem_kernel.dylib        	0x00000001ebe2f5a0 0x1ebe18000 + 95648
2   CoreFoundation                	0x00000001ec230914 0x1ec186000 + 698644
3   CoreFoundation                	0x00000001ec22b824 0x1ec186000 + 677924
4   CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
5   Foundation                    	0x00000001ecbf995c 0x1ecbf2000 + 31068
6   padkranti                     	0x00000001008123a4 0x100610000 + 2106276
7   Foundation                    	0x00000001ecd264a0 0x1ecbf2000 + 1262752
8   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
9   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
10  libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 8 name:  com.apple.NSURLConnectionLoader
Thread 8:
0   libsystem_kernel.dylib        	0x00000001ebe300f4 0x1ebe18000 + 98548
1   libsystem_kernel.dylib        	0x00000001ebe2f5a0 0x1ebe18000 + 95648
2   CoreFoundation                	0x00000001ec230914 0x1ec186000 + 698644
3   CoreFoundation                	0x00000001ec22b824 0x1ec186000 + 677924
4   CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
5   CFNetwork                     	0x00000001ec84574c 0x1ec844000 + 5964
6   Foundation                    	0x00000001ecd264a0 0x1ecbf2000 + 1262752
7   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
8   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
9   libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 9 name:  com.apple.CFSocket.private
Thread 9:
0   libsystem_kernel.dylib        	0x00000001ebe3b328 0x1ebe18000 + 144168
1   CoreFoundation                	0x00000001ec2395f8 0x1ec186000 + 734712
2   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
3   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
4   libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 10 name:  com.apple.CFStream.LegacyThread
Thread 10:
0   libsystem_kernel.dylib        	0x00000001ebe300f4 0x1ebe18000 + 98548
1   libsystem_kernel.dylib        	0x00000001ebe2f5a0 0x1ebe18000 + 95648
2   CoreFoundation                	0x00000001ec230914 0x1ec186000 + 698644
3   CoreFoundation                	0x00000001ec22b824 0x1ec186000 + 677924
4   CoreFoundation                	0x00000001ec22afb4 0x1ec186000 + 675764
5   CoreFoundation                	0x00000001ec243cf4 0x1ec186000 + 777460
6   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
7   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
8   libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 11:
0   libsystem_pthread.dylib       	0x00000001ebec0cd0 0x1ebeb2000 + 60624

Thread 12 name:  Heap Helper Thread
Thread 12:
0   libsystem_kernel.dylib        	0x00000001ebe3aee4 0x1ebe18000 + 143076
1   libsystem_pthread.dylib       	0x00000001ebeb5cf8 0x1ebeb2000 + 15608
2   JavaScriptCore                	0x00000001f348c8cc 0x1f343c000 + 329932
3   JavaScriptCore                	0x00000001f3473514 0x1f343c000 + 226580
4   JavaScriptCore                	0x00000001f3447358 0x1f343c000 + 45912
5   JavaScriptCore                	0x00000001f34476e8 0x1f343c000 + 46824
6   JavaScriptCore                	0x00000001f348ab30 0x1f343c000 + 322352
7   JavaScriptCore                	0x00000001f348c03c 0x1f343c000 + 327740
8   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
9   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
10  libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 13 name:  JSC Heap Collector Thread
Thread 13:
0   libsystem_kernel.dylib        	0x00000001ebe3aee4 0x1ebe18000 + 143076
1   libsystem_pthread.dylib       	0x00000001ebeb5cf8 0x1ebeb2000 + 15608
2   JavaScriptCore                	0x00000001f348c8cc 0x1f343c000 + 329932
3   JavaScriptCore                	0x00000001f3473514 0x1f343c000 + 226580
4   JavaScriptCore                	0x00000001f3447358 0x1f343c000 + 45912
5   JavaScriptCore                	0x00000001f34476e8 0x1f343c000 + 46824
6   JavaScriptCore                	0x00000001f348ab30 0x1f343c000 + 322352
7   JavaScriptCore                	0x00000001f348c03c 0x1f343c000 + 327740
8   libsystem_pthread.dylib       	0x00000001ebebd2c0 0x1ebeb2000 + 45760
9   libsystem_pthread.dylib       	0x00000001ebebd220 0x1ebeb2000 + 45600
10  libsystem_pthread.dylib       	0x00000001ebec0cdc 0x1ebeb2000 + 60636

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000281d93db7
    x4: 0x00000001eb46fb71   x5: 0x000000016f7ee640   x6: 0x000000000000006e   x7: 0xffffffffffffffec
    x8: 0x0000000000000800   x9: 0x00000001ebeb8888  x10: 0x00000001ebeb3f18  x11: 0x0000000000000003
   x12: 0x0000000000000000  x13: 0x0000000000000001  x14: 0x0000000000000010  x15: 0x0000000000000009
   x16: 0x0000000000000148  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000101d5ebc0  x21: 0x000000016f7ee640  x22: 0x0000000000000303  x23: 0x0000000101d5eca0
   x24: 0x0000000225acc9c0  x25: 0x0000000101d5eca0  x26: 0x0000000000000013  x27: 0x0000000000000000
   x28: 0x000000016f902040   fp: 0x000000016f7ee5a0   lr: 0x00000001ebeb4094
    sp: 0x000000016f7ee570   pc: 0x00000001ebe3b0dc cpsr: 0x00000000

**Comment by Suraj-Tiwari** [comment]
by logs seems like networking issue, reopen if someone else facing same.
