### ISSUE TITLE
Build Error! Bro need your Help

### ISSUE THREAD

**Issue by MonMohon** [Suraj-Tiwari/react-native-payumoney#52]
`Task :react-native-payumoney:compileDebugKotlin
w: F:\RNative\HindPhotostat\node_modules\react-native-payumoney\android\src\main\java\com\surajtiwari\reactnativepayumoney\PayumoneyActivity.kt: (50, 26): Parameter 'activity' is never used
w: F:\RNative\HindPhotostat\node_modules\react-native-payumoney\android\src\main\java\com\surajtiwari\reactnativepayumoney\PayumoneyActivity.kt: (54, 60): Type mismatch: inferred type is TransactionResponse? but TransactionResponse was expected
w: F:\RNative\HindPhotostat\node_modules\react-native-payumoney\android\src\main\java\com\surajtiwari\reactnativepayumoney\PayumoneyActivity.kt: (55, 44): Type mismatch: inferred type is ResultModel? but ResultModel was expected
w: F:\RNative\HindPhotostat\node_modules\react-native-payumoney\android\src\main\java\com\surajtiwari\reactnativepayumoney\PayumoneyActivity.kt: (56, 17): Condition 'transactionResponse != null' is always 'true'

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

**Comment by MonMohon** [comment]
all working just build warning

**Comment by Suraj-Tiwari** [comment]
commit https://github.com/Suraj-Tiwari/react-native-payumoney/commit/5e0929a14edcbba2c372cb64fc3de7a65cdc1d82 solves this issue
