### ISSUE TITLE
error {success: false}

### ISSUE THREAD

**Issue by i-suraj** [Suraj-Tiwari/react-native-payumoney#6]
i tried many times still getting this error...
**{success: false}**

my option parameters are as follows:-
```
amount:1
email:"test@gmail.com"
furl:"https://www.payumoney.com/mobileapp/payumoney/failure.php"
hash:"64c37b20ca532949386f04f092e379b1bad80f22a0471eed3656a0c92530961fcf4f09ed85ee9f213552d71a168dcdb80d354b5f84e3272472518d101e203d72"
id:"6308905"
key:"gez8KIo6"
name:"Name"
phone:"8826343434"
productId:"test"
sandbox:true
surl:"https://www.payumoney.com/mobileapp/payumoney/success.php"
txid:"1534073035308"
```

my salt is  rwsdJ8ZkJw

**Comment by Suraj-Tiwari** [comment]
That hash is manually defined.. if you want to test it with your data create hash using this php function and replace data accordingly

```php
<?php
echo makeHash("LLKwG0","123123123","10.0","test","Name","test@gmail.com");

function makeHash($key, $txnid, $amount, $productinfo, $firstname, $email){
    $salt = "qauKbEAJ";
    $payhash_str = $key . '|' . checkNull($txnid) . '|' . checkNull($amount) . '|' . checkNull($productinfo) . '|' . checkNull($firstname) . '|' . checkNull($email) . '|||||||||||' . $salt;
    $hash = strtolower(hash('sha512', $payhash_str));
    return $hash;
}

function checkNull($value)
{
    if ($value == null) {
        return '';
    } else {
        return $value;
    }
}

?>
```

**Comment by Suraj-Tiwari** [comment]
To know how payumoney works have a look at 
[PayuMoney Docs](https://developer.payumoney.com/android/) and check (**_Integration reference_**)

**Comment by Suraj-Tiwari** [comment]
I checked your code and found following issues

- Amount is an intiger, Must be a double ( example 1.0 ).
- I think you are using production keys so set **sandbox:false**

I tried your credentials in this function 
```php
<?php

//(key,txid,amount, productId, name,email)

echo makeHash("gez8KIo6","1534073035308","1.0","test","Name","test@gmail.com");

function makeHash($key, $txnid, $amount, $productinfo, $firstname, $email){
    $salt = "rwsdJ8ZkJw";
    $payhash_str = $key . '|' . checkNull($txnid) . '|' . checkNull($amount) . '|' . checkNull($productinfo) . '|' . checkNull($firstname) . '|' . checkNull($email) . '|||||||||||' . $salt;
    $hash = strtolower(hash('sha512', $payhash_str));
    return $hash;
}

function checkNull($value)
{
    if ($value == null) {
        return '';
    } else {
        return $value;
    }
}
``` 
and I got 
`de7f81c1c972272beea1b091d75a92556a9726b9e6118deb3e9de2ee410f0c9a11ff41d9902b92b1d2868730e467472bd69f1709a6c10c12e064d09419be8697`

this is different from your hash 
[tested on](http://phptester.net/)

**Comment by Suraj-Tiwari** [comment]
Due to inactivity closing this issue

**Comment by zesu00** [comment]
I have tried everything, but it still give me the error message {"success":false}

**Comment by i-suraj** [comment]
I had same issue but i was able to solve this just by setting the amount to as
`let amount= parseFloat("10");
`
The issue is with data type. This solution worked for me. Hope this will help you.

**Comment by manubodhi** [comment]
passing this float amount is not working for whole numbers, we have to pass transactions like 10 rupees 100 rupees and all, this will send as 10 only and causing issue taking it as integer and crashing the SDK.
