### ISSUE TITLE
key is not valid

### ISSUE THREAD

**Issue by swaroopaillinda** [Suraj-Tiwari/react-native-payumoney#60]
hi I am using this for doing payumoney in  my react native applications

` const payData = {
             amount: '1.0',//data.amount.toString(),
             txnId: data.txnid,
             productName: data.productinfo,
             firstName: data.firstname ? data.firstName : "Sample",
            email: data.email,
            phone: data.phone,
            merchantId: '<myid>',
            key: 'mykey>',
            successUrl: data.surl,//'https://www.payumoney.com/mobileapp/payumoney/success.php',
            failedUrl: data.furl,//'https://www.payumoney.com/mobileapp/payumoney/failure.php',
            isDsebug: false,
       
            hash:data.hash,
         };
         console.log("dnfldk",data)
        Payumoney(payData).then((data) => {
           
            console.log("Success, code",data)
         }).catch((e) => {
          
            console.log("Failed, code",e)
        })`

this is my code 
but when running in ios its showing the key is invalid
in android showing some error occured 
can you tell me whats the issues is the key is working fine with my web applkication

**Comment by Suraj-Tiwari** [comment]
please test with testing keys first if issue remains open this issue again
