### ISSUE TITLE
Build Fail 

### ISSUE THREAD

**Issue by ap9086013** [Suraj-Tiwari/react-native-payumoney#61]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.payumoney.sdkui:plug-n-play:1.6.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
       - file:/C:/Users/Ankur/.m2/repository/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
       - file:/I:/SoftGrid/React_Native/test/node_modules/react-native/android/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
       - file:/I:/SoftGrid/React_Native/test/node_modules/jsc-android/dist/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
       - https://dl.google.com/dl/android/maven2/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
       - https://www.jitpack.io/com/payumoney/sdkui/plug-n-play/1.6.1/plug-n-play-1.6.1.pom
     Required by:
         project :app > project :react-native-payumoney

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 25s

**Comment by Suraj-Tiwari** [comment]
https://github.com/Suraj-Tiwari/react-native-payumoney/blob/c366d8ce6db21ddf9c0f62ff95082a2659126cd2/example/android/build.gradle#L35

add `jcenter()` in your android/build.gradle like that
