### ISSUE TITLE
Could not resolve com.payumoney.sdkui:plug-n-play:1.6.1

### ISSUE THREAD

**Issue by lalit-suthar-dev** [Suraj-Tiwari/react-native-payumoney#62]
Greetings I am getting this error when running the project in android after installing react-native-payumpney, can you please help.
<img width="1728" alt="Screenshot 2021-12-14 at 6 58 53 PM" src="https://user-images.githubusercontent.com/87010360/146007394-b27cb3de-ce07-4172-b7d0-b7b552d83b3e.png">
.

**Comment by ap9086013** [comment]
Same problem

**Comment by Suraj-Tiwari** [comment]
okay. thanks for report, I'll have a look.

**Comment by Suraj-Tiwari** [comment]
https://github.com/Suraj-Tiwari/react-native-payumoney/blob/c366d8ce6db21ddf9c0f62ff95082a2659126cd2/example/android/build.gradle#L35

add `jcenter()` in your android/build.gradle like that
